apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventplanner-ingress
  namespace: eventplanner
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx   # recommended if your k8s version supports it
  rules:
    - host: eventplanner.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080



